apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: aiops-demo
  region: ap-southeast-1
  version: "1.29"

managedNodeGroups:
  - name: workers
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 30
    ssh:
      allow: false
    iam:
      withAddonPolicies:
        cloudWatch: true
        
cloudWatch:
  clusterLogging:
    enableTypes:
      - api
      - audit
      - authenticator
