"""
Tests to boost coverage for the 3 lowest-coverage modules:
  1. src/aws_ops.py (44%)
  2. src/aci/interface.py (47%)
  3. src/aws_scanner.py (56%)

Generated by daily quality check — 2026-03-08.
"""

import pytest
from unittest.mock import MagicMock, patch
from datetime import datetime, timezone
from botocore.exceptions import ClientError


# =============================================================================
# 1. aws_ops.py — VPC, ELB, DynamoDB, ElastiCache health checks
# =============================================================================

class TestAWSServiceOpsVPC:
    """Cover vpc_health_check (lines 905-1003)."""

    @pytest.fixture
    def ops(self):
        with patch("boto3.Session"):
            from src.aws_ops import AWSServiceOps
            return AWSServiceOps(region="us-east-1")

    def test_vpc_health_check_healthy(self, ops):
        ec2 = MagicMock()
        ops._get_client = MagicMock(return_value=ec2)
        ec2.describe_vpcs.return_value = {
            "Vpcs": [{
                "VpcId": "vpc-123", "State": "available", "IsDefault": True,
                "CidrBlock": "10.0.0.0/16",
                "Tags": [{"Key": "Name", "Value": "main-vpc"}],
            }]
        }
        ec2.describe_subnets.return_value = {"Subnets": [{"SubnetId": "sub-1", "State": "available"}]}
        ec2.describe_internet_gateways.return_value = {"InternetGateways": [{"InternetGatewayId": "igw-1"}]}
        ec2.describe_nat_gateways.return_value = {"NatGateways": []}

        result = ops.vpc_health_check()
        assert result["service"] == "VPC"
        assert result["overall_status"] == "healthy"
        assert result["vpcs"][0]["name"] == "main-vpc"

    def test_vpc_health_check_specific_vpc(self, ops):
        ec2 = MagicMock()
        ops._get_client = MagicMock(return_value=ec2)
        ec2.describe_vpcs.return_value = {"Vpcs": [{"VpcId": "vpc-456", "State": "available", "IsDefault": False, "CidrBlock": "172.16.0.0/16", "Tags": []}]}
        ec2.describe_subnets.return_value = {"Subnets": []}
        ec2.describe_internet_gateways.return_value = {"InternetGateways": []}
        ec2.describe_nat_gateways.return_value = {"NatGateways": []}

        result = ops.vpc_health_check(vpc_id="vpc-456")
        ec2.describe_vpcs.assert_called_with(VpcIds=["vpc-456"])

    def test_vpc_health_check_unhealthy(self, ops):
        ec2 = MagicMock()
        ops._get_client = MagicMock(return_value=ec2)
        ec2.describe_vpcs.return_value = {"Vpcs": [{"VpcId": "vpc-789", "State": "pending", "CidrBlock": "10.1.0.0/16", "Tags": []}]}
        ec2.describe_subnets.return_value = {"Subnets": []}
        ec2.describe_internet_gateways.return_value = {"InternetGateways": []}
        ec2.describe_nat_gateways.return_value = {"NatGateways": []}

        result = ops.vpc_health_check()
        assert result["vpcs"][0]["health"] == "unhealthy"

    def test_vpc_health_check_nat_warning(self, ops):
        ec2 = MagicMock()
        ops._get_client = MagicMock(return_value=ec2)
        ec2.describe_vpcs.return_value = {"Vpcs": [{"VpcId": "vpc-nat", "State": "available", "CidrBlock": "10.2.0.0/16", "Tags": []}]}
        ec2.describe_subnets.return_value = {"Subnets": [{"SubnetId": "sub-1", "State": "available"}, {"SubnetId": "sub-2", "State": "pending"}]}
        ec2.describe_internet_gateways.return_value = {"InternetGateways": []}
        ec2.describe_nat_gateways.return_value = {"NatGateways": [{"NatGatewayId": "nat-1", "State": "available"}, {"NatGatewayId": "nat-2", "State": "failed"}]}

        result = ops.vpc_health_check()
        assert result["vpcs"][0]["health"] == "warning"

    def test_vpc_health_check_client_error(self, ops):
        ec2 = MagicMock()
        ops._get_client = MagicMock(return_value=ec2)
        ec2.describe_vpcs.side_effect = ClientError({"Error": {"Code": "UnauthorizedAccess", "Message": "no"}}, "DescribeVpcs")
        result = ops.vpc_health_check()
        assert "error" in str(result).lower() or result["overall_status"] != "healthy"


class TestAWSServiceOpsELB:
    """Cover elb_health_check (lines 1050-1138)."""

    @pytest.fixture
    def ops(self):
        with patch("boto3.Session"):
            from src.aws_ops import AWSServiceOps
            return AWSServiceOps(region="us-east-1")

    def test_elb_healthy(self, ops):
        elbv2 = MagicMock()
        ops._get_client = MagicMock(return_value=elbv2)
        elbv2.describe_load_balancers.return_value = {"LoadBalancers": [{
            "LoadBalancerArn": "arn:lb/app/my-lb/abc", "LoadBalancerName": "my-lb",
            "State": {"Code": "active"}, "Type": "application", "Scheme": "internet-facing", "DNSName": "my-lb.elb.amazonaws.com",
        }]}
        elbv2.describe_target_groups.return_value = {"TargetGroups": [{"TargetGroupArn": "arn:tg/tg1"}]}
        elbv2.describe_target_health.return_value = {"TargetHealthDescriptions": [{"TargetHealth": {"State": "healthy"}, "Target": {"Id": "i-1"}}]}

        result = ops.elb_health_check()
        assert result["service"] == "ELB"
        assert result["overall_status"] == "healthy"

    def test_elb_with_name(self, ops):
        elbv2 = MagicMock()
        ops._get_client = MagicMock(return_value=elbv2)
        elbv2.describe_load_balancers.return_value = {"LoadBalancers": []}
        result = ops.elb_health_check(lb_name="my-lb")
        elbv2.describe_load_balancers.assert_called_with(Names=["my-lb"])

    def test_elb_unhealthy_targets(self, ops):
        elbv2 = MagicMock()
        ops._get_client = MagicMock(return_value=elbv2)
        elbv2.describe_load_balancers.return_value = {"LoadBalancers": [{
            "LoadBalancerArn": "arn:lb/app/lb2/xyz", "LoadBalancerName": "lb2",
            "State": {"Code": "active"}, "Type": "application", "Scheme": "internal", "DNSName": "lb2.internal",
        }]}
        elbv2.describe_target_groups.return_value = {"TargetGroups": [{"TargetGroupArn": "arn:tg/tg2"}]}
        elbv2.describe_target_health.return_value = {"TargetHealthDescriptions": [
            {"TargetHealth": {"State": "unhealthy"}, "Target": {"Id": "i-1"}},
            {"TargetHealth": {"State": "healthy"}, "Target": {"Id": "i-2"}},
        ]}

        result = ops.elb_health_check()
        assert result["load_balancers"][0]["unhealthy_targets"] == 1
        assert result["load_balancers"][0]["health"] == "warning"

    def test_elb_no_targets(self, ops):
        elbv2 = MagicMock()
        ops._get_client = MagicMock(return_value=elbv2)
        elbv2.describe_load_balancers.return_value = {"LoadBalancers": [{
            "LoadBalancerArn": "arn:lb/app/lb3/xyz", "LoadBalancerName": "lb3",
            "State": {"Code": "active"}, "Type": "network", "Scheme": "internet-facing", "DNSName": "lb3.dns",
        }]}
        elbv2.describe_target_groups.return_value = {"TargetGroups": [{"TargetGroupArn": "arn:tg/tg3"}]}
        elbv2.describe_target_health.return_value = {"TargetHealthDescriptions": []}

        result = ops.elb_health_check()
        lb = result["load_balancers"][0]
        assert lb["total_targets"] == 0
        assert "No registered targets" in str(lb["issues"])


class TestAWSServiceOpsDynamoDB:
    """Cover dynamodb_health_check + dynamodb_scan (lines 1315-1480)."""

    @pytest.fixture
    def ops(self):
        with patch("boto3.Session"):
            from src.aws_ops import AWSServiceOps
            return AWSServiceOps(region="us-east-1")

    def test_dynamodb_health_check(self, ops):
        ddb = MagicMock()
        ops._get_client = MagicMock(return_value=ddb)
        ddb.list_tables.return_value = {"TableNames": ["users"]}
        ddb.describe_table.return_value = {"Table": {
            "TableName": "users", "TableStatus": "ACTIVE", "ItemCount": 1000,
            "TableSizeBytes": 50000,
            "ProvisionedThroughput": {"ReadCapacityUnits": 5, "WriteCapacityUnits": 5},
            "TableArn": "arn:aws:dynamodb:us-east-1:123:table/users",
            "GlobalSecondaryIndexes": [],
        }}
        result = ops.dynamodb_health_check(table_name="users")
        assert result["service"] == "DynamoDB"

    def test_dynamodb_scan(self, ops):
        ddb = MagicMock()
        ops._get_client = MagicMock(return_value=ddb)
        ddb.list_tables.return_value = {"TableNames": ["t1", "t2"]}
        ddb.describe_table.side_effect = [
            {"Table": {"TableName": "t1", "TableStatus": "ACTIVE", "ItemCount": 500, "TableSizeBytes": 10000,
                        "ProvisionedThroughput": {"ReadCapacityUnits": 5, "WriteCapacityUnits": 5}, "TableArn": "arn:t1"}},
            {"Table": {"TableName": "t2", "TableStatus": "ACTIVE", "ItemCount": 100, "TableSizeBytes": 2000,
                        "ProvisionedThroughput": {"ReadCapacityUnits": 1, "WriteCapacityUnits": 1}, "TableArn": "arn:t2"}},
        ]
        result = ops.dynamodb_scan()
        assert result["count"] == 2
        assert len(result["tables"]) == 2

    def test_dynamodb_get_metrics(self, ops):
        cw = MagicMock()
        ops._get_client = MagicMock(return_value=cw)
        cw.get_metric_statistics.return_value = {"Datapoints": [{"Timestamp": datetime.now(timezone.utc), "Sum": 100.0, "Unit": "Count"}]}
        result = ops.dynamodb_get_metrics(table_name="users", hours=1)
        assert "table_name" in result or "metrics" in result or "service" in result


class TestAWSServiceOpsElastiCache:
    """Cover elasticache_health_check + elasticache_scan (lines 1618-1781)."""

    @pytest.fixture
    def ops(self):
        with patch("boto3.Session"):
            from src.aws_ops import AWSServiceOps
            obj = AWSServiceOps(region="us-east-1")
            return obj

    def _mock_cw_client(self, ops, ec):
        """Set up ops to return ec for elasticache and a CW mock for cloudwatch."""
        cw = MagicMock()
        cw.get_metric_statistics.return_value = {"Datapoints": []}

        def side_effect(service):
            if service == "cloudwatch":
                return cw
            return ec
        ops._get_client = MagicMock(side_effect=side_effect)

    def test_elasticache_health_check_all(self, ops):
        ec = MagicMock()
        self._mock_cw_client(ops, ec)
        ec.describe_cache_clusters.return_value = {"CacheClusters": [{
            "CacheClusterId": "redis-001", "CacheNodeType": "cache.t3.micro",
            "Engine": "redis", "EngineVersion": "7.0", "CacheClusterStatus": "available",
            "NumCacheNodes": 1, "CacheNodes": [{"CacheNodeId": "0001", "CacheNodeStatus": "available"}],
        }]}
        result = ops.elasticache_health_check()
        assert result["service"] == "ElastiCache"

    def test_elasticache_health_check_specific(self, ops):
        ec = MagicMock()
        self._mock_cw_client(ops, ec)
        ec.describe_cache_clusters.return_value = {"CacheClusters": [{
            "CacheClusterId": "redis-002", "CacheNodeType": "cache.r6g.large",
            "Engine": "redis", "EngineVersion": "7.0", "CacheClusterStatus": "available",
            "NumCacheNodes": 2,
            "CacheNodes": [{"CacheNodeId": "0001", "CacheNodeStatus": "available"}, {"CacheNodeId": "0002", "CacheNodeStatus": "available"}],
        }]}
        result = ops.elasticache_health_check(cluster_id="redis-002")
        ec.describe_cache_clusters.assert_called_with(CacheClusterId="redis-002", ShowCacheNodeInfo=True)

    def test_elasticache_scan(self, ops):
        ec = MagicMock()
        ops._get_client = MagicMock(return_value=ec)
        ec.describe_cache_clusters.return_value = {"CacheClusters": [{
            "CacheClusterId": "redis-001", "CacheNodeType": "cache.t3.micro",
            "Engine": "redis", "EngineVersion": "7.0", "CacheClusterStatus": "available", "NumCacheNodes": 1,
        }]}
        ec.describe_replication_groups.return_value = {"ReplicationGroups": []}
        result = ops.elasticache_scan()
        assert "clusters" in result or "count" in result


# =============================================================================
# 2. aci/interface.py — get_metrics, kubectl
# =============================================================================

class TestACIInterfaceExtended:
    """Cover get_metrics and kubectl (lines 336-544)."""

    @pytest.fixture
    def aci(self):
        with patch("src.aci.interface.KubectlExecutor") as mk, \
             patch("src.aci.interface.ShellExecutor") as ms, \
             patch("src.aci.interface.LogsProvider") as ml, \
             patch("src.aci.interface.EventsProvider") as me, \
             patch("src.aci.interface.MetricsProvider") as mm, \
             patch("src.aci.interface.SecurityFilter") as msec, \
             patch("src.aci.interface.AuditLogger") as ma:

            sec = msec.return_value
            sec.validate_namespace.return_value = True
            sec.filter_sensitive_data.side_effect = lambda x: x

            from src.aci.interface import AgentCloudInterface
            instance = AgentCloudInterface(cluster_name="test-cluster")
            instance._kubectl = mk.return_value
            instance._shell = ms.return_value
            instance._logs = ml.return_value
            instance._events = me.return_value
            instance._metrics = mm.return_value
            instance._security = sec
            instance._audit = ma.return_value
            return instance

    def test_get_metrics(self, aci):
        from src.aci.models import TelemetryResult, ResultStatus
        aci._metrics.get_metrics.return_value = TelemetryResult(
            status=ResultStatus.SUCCESS,
            data=[{"cpu": "50m", "memory": "128Mi"}],
        )
        result = aci.get_metrics(namespace="default")
        assert result.status == ResultStatus.SUCCESS

    def test_get_metrics_with_query(self, aci):
        from src.aci.models import TelemetryResult, ResultStatus
        aci._metrics.get_metrics.return_value = TelemetryResult(
            status=ResultStatus.SUCCESS,
            data=[{"cpu": "100m"}],
        )
        result = aci.get_metrics(namespace="default", query="cpu_usage")
        assert result.status == ResultStatus.SUCCESS

    def test_kubectl_read_only(self, aci):
        from src.aci.models import OperationResult, ResultStatus
        aci._security.is_read_only_command.return_value = True
        aci._security.check_kubectl.return_value = (True, "allowed")
        aci._kubectl.execute.return_value = OperationResult(
            status=ResultStatus.SUCCESS,
            stdout="NAME   READY   STATUS",
            command="kubectl get pods -n default",
        )
        result = aci.kubectl(["get", "pods", "-n", "default"])
        assert result.status == ResultStatus.SUCCESS

    def test_kubectl_write_blocked(self, aci):
        from src.aci.models import ResultStatus
        aci._security.check_kubectl.return_value = (False, "write operation blocked in safe mode")
        result = aci.kubectl(["delete", "pod", "nginx"])
        assert result.status == ResultStatus.ERROR


# =============================================================================
# 3. aws_scanner.py — private scan methods via scan_all_resources
# =============================================================================

class TestAWSCloudScannerExtended:
    """Cover _scan_rds, _scan_lambda, _scan_s3, _scan_vpc via scan_all_resources."""

    @pytest.fixture
    def scanner(self):
        with patch("boto3.Session") as mock_session:
            from src.aws_scanner import AWSCloudScanner
            s = AWSCloudScanner(region="us-east-1")
            s._session = mock_session.return_value
            return s

    def test_scan_rds_private(self, scanner):
        rds = MagicMock()
        scanner._session.client.return_value = rds
        rds.describe_db_instances.return_value = {"DBInstances": [{
            "DBInstanceIdentifier": "mydb", "DBInstanceClass": "db.t3.micro",
            "Engine": "mysql", "EngineVersion": "8.0", "DBInstanceStatus": "available",
            "MasterUsername": "admin", "Endpoint": {"Address": "mydb.rds.amazonaws.com", "Port": 3306},
            "AllocatedStorage": 20, "MultiAZ": False, "StorageEncrypted": True,
        }]}
        result = scanner._scan_rds()
        assert result["count"] >= 1

    def test_scan_lambda_private(self, scanner):
        lmb = MagicMock()
        scanner._session.client.return_value = lmb
        lmb.list_functions.return_value = {"Functions": [{
            "FunctionName": "my-func", "Runtime": "python3.12", "MemorySize": 128,
            "Timeout": 30, "CodeSize": 5000, "LastModified": "2026-03-01T00:00:00Z",
            "FunctionArn": "arn:aws:lambda:us-east-1:123:function:my-func",
        }]}
        result = scanner._scan_lambda()
        assert result["count"] >= 1

    def test_scan_s3_private(self, scanner):
        s3 = MagicMock()
        scanner._session.client.return_value = s3
        s3.list_buckets.return_value = {"Buckets": [{"Name": "my-bucket", "CreationDate": datetime(2025, 1, 1, tzinfo=timezone.utc)}]}
        result = scanner._scan_s3()
        assert result["count"] >= 1

    def test_scan_vpc_private(self, scanner):
        ec2 = MagicMock()
        scanner._session.client.return_value = ec2
        ec2.describe_vpcs.return_value = {"Vpcs": [{
            "VpcId": "vpc-abc", "State": "available", "CidrBlock": "10.0.0.0/16",
            "IsDefault": True, "Tags": [{"Key": "Name", "Value": "default"}],
        }]}
        ec2.describe_subnets.return_value = {"Subnets": [{"SubnetId": "sub-1", "State": "available", "CidrBlock": "10.0.1.0/24", "AvailabilityZone": "us-east-1a"}]}
        ec2.describe_security_groups.return_value = {"SecurityGroups": [{"GroupId": "sg-1", "GroupName": "default", "Description": "default", "IpPermissions": [], "IpPermissionsEgress": []}]}
        result = scanner._scan_vpc()
        assert result["count"] >= 1

    def test_scan_ecs_private(self, scanner):
        ecs = MagicMock()
        scanner._session.client.return_value = ecs
        ecs.list_clusters.return_value = {"clusterArns": ["arn:aws:ecs:us-east-1:123:cluster/my-cluster"]}
        ecs.describe_clusters.return_value = {"clusters": [{
            "clusterName": "my-cluster", "clusterArn": "arn:aws:ecs:us-east-1:123:cluster/my-cluster",
            "status": "ACTIVE", "registeredContainerInstancesCount": 2,
            "runningTasksCount": 5, "pendingTasksCount": 0, "activeServicesCount": 3,
        }]}
        ecs.list_services.return_value = {"serviceArns": []}
        result = scanner._scan_ecs()
        assert result["count"] >= 1

    def test_scan_all_resources(self, scanner):
        """Integration: scan_all_resources calls all private scanners."""
        # Mock all clients to return empty results
        mock_client = MagicMock()
        scanner._session.client.return_value = mock_client

        mock_client.describe_instances.return_value = {"Reservations": []}
        mock_client.describe_db_instances.return_value = {"DBInstances": []}
        mock_client.list_functions.return_value = {"Functions": []}
        mock_client.list_buckets.return_value = {"Buckets": []}
        mock_client.describe_vpcs.return_value = {"Vpcs": []}
        mock_client.list_clusters.return_value = {"clusterArns": []}
        mock_client.describe_subnets.return_value = {"Subnets": []}
        mock_client.describe_security_groups.return_value = {"SecurityGroups": []}

        result = scanner.scan_all_resources()
        assert "services" in result or "results" in result or isinstance(result, dict)
